import Link from 'next/link'
import { createClient } from '@supabase/supabase-js'
import { currentIsoWeek, formatWeekId, formatWeekPeriod } from '@/lib/iso-week'

export const dynamic = 'force-dynamic'
export const revalidate = 600

export const metadata = {
  title: 'Weekly Digest · AgentCrush',
  description: 'Weekly signal digest from the AgentCrush index — ranking moves, ecosystem events, protocol activity.',
  alternates: {
    canonical: 'https://agentcrush.xyz/weekly',
    types: { 'application/rss+xml': 'https://agentcrush.xyz/weekly.xml' },
  },
}

// Hand-curated issues with editorial summaries.
const CURATED = [
  {
    week: '2026-W23',
    label: 'W23 · June 2–8, 2026',
    summary: 'MCP Server Index launches as the 5th category ranking. ERC-8004 trust layer tooling arrives in a cluster (Boon, Argus, avisradar). Autonomous pipeline — 8 timers — goes live.',
    href: '/weekly/2026-W23',
  },
  {
    week: '2026-W22',
    label: 'W22 · May 25–31, 2026',
    summary: 'Confidence tiers extended to every category, risk-flag infrastructure ships, and the Agent Payments Stack gets its full LLM Gateway treatment.',
    href: '/weekly/2026-W22',
  },
  {
    week: '2026-W21',
    label: 'W21 · May 18–24, 2026',
    summary: 'Where the four category rankings stand, the Agent Payments Stack index goes live, and confidence tiers ship on every score.',
    href: '/weekly/2026-W21',
  },
]

function db() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  return createClient(url, key)
}

async function autoGenerated() {
  // List of week_ids in the Supabase weekly_digest_sections table (excluding curated weeks).
  try {
    const supabase = db()
    const { data } = await supabase
      .from('weekly_digest_sections')
      .select('week_id, briefs_included, generated_at')
      .order('week_id', { ascending: false })
    if (!data) return []
    const curatedSet = new Set(CURATED.map(c => c.week))
    return data
      .filter(r => !curatedSet.has(r.week_id))
      .map(r => ({
        week: r.week_id,
        label: (() => {
          const m = r.week_id.match(/^(\d{4})-W(\d{1,2})$/)
          if (!m) return r.week_id
          return `W${Number(m[2])} · ${formatWeekPeriod(Number(m[1]), Number(m[2]))}`
        })(),
        summary: `Auto-generated digest distilled from ${r.briefs_included} daily Ajsa briefs.`,
        href: `/weekly/${r.week_id}`,
      }))
  } catch {
    return []
  }
}

export default async function WeeklyIndexPage() {
  const auto = await autoGenerated()
  // Merge: auto-generated weeks (newest first) above curated, dedup
  const seen = new Set()
  const issues = [...auto, ...CURATED].filter(i => {
    if (seen.has(i.week)) return false
    seen.add(i.week)
    return true
  })

  return (
    <main className="mx-auto max-w-[720px] px-4 md:px-6 py-14">

      <div className="mb-8">
        <p className="text-xs font-semibold uppercase tracking-widest text-[#00d4ff]/70 mb-2">
          Weekly Digest
        </p>
        <h1 className="text-2xl font-bold text-white tracking-tight">
          AgentCrush Weekly
        </h1>
        <p className="mt-2 text-sm text-white/40 leading-relaxed max-w-lg">
          Every week: ranking moves across all four category rankings, ecosystem signals distilled from
          7 days of Ajsa social briefs, and protocol activity. Auto-generated Sundays 19:00 UTC.
        </p>
        <div className="mt-4 flex flex-wrap gap-3">
          <a
            href="/weekly.xml"
            className="text-xs font-mono text-[#00d4ff]/70 hover:text-[#00d4ff] transition-colors border border-[#00d4ff]/20 rounded px-3 py-1.5"
          >
            RSS feed →
          </a>
        </div>
      </div>

      <div className="space-y-4">
        {issues.map((issue) => (
          <Link
            key={issue.week}
            href={issue.href}
            className="block rounded-lg border border-white/[0.07] bg-white/[0.02] px-5 py-4 hover:border-white/[0.14] hover:bg-white/[0.04] transition-colors group"
          >
            <div className="flex items-baseline gap-3 mb-1">
              <span className="text-xs font-mono text-[#00d4ff]/70">{issue.label}</span>
            </div>
            <p className="text-sm text-white/60 leading-relaxed group-hover:text-white/80 transition-colors">
              {issue.summary}
            </p>
            <p className="text-xs font-mono text-violet-400/50 mt-2 group-hover:text-violet-300 transition-colors">
              Read →
            </p>
          </Link>
        ))}
      </div>

    </main>
  )
}
